### ISSUE TITLE
Create symlink on Desktop

### ISSUE THREAD

**Issue by neofright** [nickzman/symboliclinker#18]
Hi,

Thank you for this fantastic service.

I noticed in the code you have the function `MakeSymbolicLinkToDesktop` and the logic around it to check if (as I understand it) if the first component of the path equals `/Volumes` then the symlink should be created on the Desktop.

I have been creating directory symlinks on `/Volumes/tank` for an smb mounted ZFS dataset but I noticed that the symlinks created are in the form of `"%s symlink"`.

(I am an XFCE refugee now using macOS and I had become accustomed to Thunar's behaviour of ["Send to > Desktop (Create Link)"](https://docs.xfce.org/xfce/thunar/send-to).)

My questions are:
1) Is this expected behaviour for this path location e.g. `/Volumes/tank/Music/albums/Artist/Album`
2) If the answer to 1 is yes: Would changing the default behaviour be as simple as replacing the calls to `MakeSymbolicLink` with `MakeSymbolicLinkToDesktop` in `SLAppDelegate.m`?

Thanks in advance

**Comment by nickzman** [comment]
Yes and yes. Links are made on the desktop only in the situations where (1) the item being linked is a volume, assuming the user didn't change the default mount path from /Volumes to somewhere else (which is very uncommon), or (2) the item's parent directory is read-only for the user. This is consistent with the Finder's behavior when you try to make an alias of some item.
