### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by paulhildebrandt** [nickzman/symboliclinker#20]
This is a great utility.  I wish that macos had it built in.   Is it possible for you to add a LICENSE file or somehow indicate the licensing?  If you don't have strong feelings an MIT license (https://opensource.org/license/mit/) would be appreciated.

**Comment by nickzman** [comment]
The license is the Modified BSD license, and it’s in the header & source of each file in the project.

**Comment by paulhildebrandt** [comment]
Thank you!
