### ISSUE TITLE
perpetual loop creating thousands of links on desktop

### ISSUE THREAD

**Issue by vsmash** [nickzman/symboliclinker#8]
G'day. I installed this as per instructions then attempted to create a symlink in a protected area. Saw nothing so tried again. After that I read your info and realised they both must be on the desktop. Upon looking at the desktop I found 3584 symbolic link folders which increased to 5000 and more as I was looking at them and attempting to delete.

**Comment by nickzman** [comment]
I cannot reproduce the problem. Can you debug it in Xcode, please?
